# Generated by Django 4.2.26 on 2025-11-26 01:05

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('parroquia_destino', models.CharField(choices=[('GONZALEZ_SUAREZ', 'URBANA: GONZÁLEZ SUÁREZ (NORTE)'), ('TULCAN_CENTRO', 'URBANA: TULCÁN (CENTRO/SUR)'), ('MALDONADO', 'RURAL: MALDONADO'), ('CHICAL', 'RURAL: CHICAL'), ('TOBAR DONOSO', 'RURAL: TOBAR DONOSO'), ('EL CARMELO', 'RURAL: EL CARMELO'), ('URBINA', 'RURAL: URBINA'), ('JULIO ANDRADE', 'RURAL: JULIO ANDRADE'), ('PIOTER', 'RURAL: PIOTER'), ('SANTA MARTHA', 'RURAL: SANTA MARTHA DE CUBA'), ('TUFIÑO', 'RURAL: TUFIÑO')], max_length=50)),
                ('capacidad_manana', models.PositiveIntegerField(default=6)),
                ('capacidad_tarde', models.PositiveIntegerField(default=4)),
                ('cupos_habilitados', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('fecha', 'parroquia_destino')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo_id', models.IntegerField(default=1, editable=False, unique=True)),
                ('def_capacidad_manana', models.PositiveIntegerField(default=6, verbose_name='Defecto Mañana')),
                ('def_capacidad_tarde', models.PositiveIntegerField(default=4, verbose_name='Defecto Tarde')),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(max_length=255, verbose_name='Nombre Comercial')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('parroquia', models.CharField(choices=[('GONZALEZ_SUAREZ', 'URBANA: GONZÁLEZ SUÁREZ (NORTE)'), ('TULCAN_CENTRO', 'URBANA: TULCÁN (CENTRO/SUR)'), ('MALDONADO', 'RURAL: MALDONADO'), ('CHICAL', 'RURAL: CHICAL'), ('TOBAR DONOSO', 'RURAL: TOBAR DONOSO'), ('EL CARMELO', 'RURAL: EL CARMELO'), ('URBINA', 'RURAL: URBINA'), ('JULIO ANDRADE', 'RURAL: JULIO ANDRADE'), ('PIOTER', 'RURAL: PIOTER'), ('SANTA MARTHA', 'RURAL: SANTA MARTHA DE CUBA'), ('TUFIÑO', 'RURAL: TUFIÑO')], max_length=50)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('ubicacion_verificada', models.BooleanField(default=False, verbose_name='Ubicación Confirmada por Usuario')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('DOC', '1. Documentación Habilitante'), ('PQS', '2. Sistema Contra Incendios (Extintores)'), ('SEN', '3. Señalética y Evacuación'), ('ELE', '4. Sistema Eléctrico'), ('GLP', '5. Manejo de Gas (GLP)'), ('GEN', '6. Requisitos Generales')], default='GEN', max_length=3, verbose_name='Categoría')),
                ('titulo', models.CharField(max_length=200, verbose_name='Ítem')),
                ('contenido', models.TextField(verbose_name='Especificación Técnica')),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='N° Orden')),
            ],
            options={
                'verbose_name': 'Requisito Legal',
                'ordering': ['seccion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.CharField(choices=[('MANANA', 'MAÑANA'), ('TARDE', 'TARDE')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('CONFIRMADO', 'CONFIRMADO'), ('RECHAZADO', 'RECHAZADO'), ('TERMINADO', 'TERMINADO (Inspección Exitosa)'), ('CANCELADO', 'CANCELADO (Por Usuario/Staff)'), ('NO_REALIZADA', 'NO REALIZADA (Ausente/Incumplido)')], default='PENDIENTE', max_length=20)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('referencia_ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_formulario', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Formulario')),
                ('motivo_cancelacion', models.TextField(blank=True, null=True, verbose_name='Motivo Cancelación')),
                ('hora_estimada', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.agendadiaria')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.establecimiento')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TasaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='Permiso de Funcionamiento Anual', max_length=255, verbose_name='Detalle')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor ($)')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Dejar en 0 para auto-asignar al final')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.tipoestablecimiento', verbose_name='Giro de Negocio')),
            ],
            options={
                'verbose_name': 'Tasa de Pago',
                'ordering': ['orden', 'tipo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('fecha_ultima_actualizacion', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('SUCCESS', 'Éxito'), ('WARNING', 'Alerta'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoestablecimiento', verbose_name='Giro de Negocio'),
        ),
    ]
